export interface ElementData {
  number: number;
  symbol: string;
  name: string;
  atomic_mass: number;
  category: string;
  group: number;
  period: number;
  phase: string;
  appearance: string | null;
  boiling_point: number | null;
  melting_point: number | null;
  density: number | null;
  summary: string;
  electron_configuration: string;
  cpk_hex: string;
}

export const elements: ElementData[] = [
  {
    number: 1,
    symbol: "H",
    name: "Hydrogen",
    atomic_mass: 1.008,
    category: "diatomic nonmetal",
    group: 1,
    period: 1,
    phase: "Gas",
    appearance: "colorless gas",
    boiling_point: 20.271,
    melting_point: 13.99,
    density: 0.08988,
    summary: "Hydrogen is the chemical element with the symbol H and atomic number 1. With a standard atomic weight of 1.008, hydrogen is the lightest element on the periodic table.",
    electron_configuration: "1s1",
    cpk_hex: "ffffff"
  },
  {
    number: 2,
    symbol: "He",
    name: "Helium",
    atomic_mass: 4.0026,
    category: "noble gas",
    group: 18,
    period: 1,
    phase: "Gas",
    appearance: "colorless gas, exhibiting a red-orange glow when placed in a high-voltage electric field",
    boiling_point: 4.222,
    melting_point: 0.95,
    density: 0.1786,
    summary: "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas that heads the noble gas group in the periodic table.",
    electron_configuration: "1s2",
    cpk_hex: "d9ffff"
  },
  {
    number: 3,
    symbol: "Li",
    name: "Lithium",
    atomic_mass: 6.94,
    category: "alkali metal",
    group: 1,
    period: 2,
    phase: "Solid",
    appearance: "silvery-white",
    boiling_point: 1603,
    melting_point: 453.65,
    density: 0.534,
    summary: "Lithium is a chemical element with symbol Li and atomic number 3. It is a soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the lightest solid element.",
    electron_configuration: "[He] 2s1",
    cpk_hex: "cc80ff"
  },
  {
    number: 4,
    symbol: "Be",
    name: "Beryllium",
    atomic_mass: 9.0122,
    category: "alkaline earth metal",
    group: 2,
    period: 2,
    phase: "Solid",
    appearance: "white-gray metal",
    boiling_point: 2742,
    melting_point: 1560,
    density: 1.85,
    summary: "Beryllium is a chemical element with symbol Be and atomic number 4. It is a relatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei that have collided with cosmic rays.",
    electron_configuration: "[He] 2s2",
    cpk_hex: "c2ff00"
  },
  {
    number: 5,
    symbol: "B",
    name: "Boron",
    atomic_mass: 10.81,
    category: "metalloid",
    group: 13,
    period: 2,
    phase: "Solid",
    appearance: "black-brown",
    boiling_point: 4273,
    melting_point: 2349,
    density: 2.08,
    summary: "Boron is a chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in the Solar system and in the Earth's crust.",
    electron_configuration: "[He] 2s2 2p1",
    cpk_hex: "ffb5b5"
  },
  {
    number: 6,
    symbol: "C",
    name: "Carbon",
    atomic_mass: 12.011,
    category: "polyatomic nonmetal",
    group: 14,
    period: 2,
    phase: "Solid",
    appearance: null,
    boiling_point: null,
    melting_point: null,
    density: 2.267,
    summary: "Carbon is a chemical element with symbol C and atomic number 6. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds. It belongs to group 14 of the periodic table.",
    electron_configuration: "[He] 2s2 2p2",
    cpk_hex: "909090"
  },
  {
    number: 7,
    symbol: "N",
    name: "Nitrogen",
    atomic_mass: 14.007,
    category: "diatomic nonmetal",
    group: 15,
    period: 2,
    phase: "Gas",
    appearance: "colorless gas, liquid or solid",
    boiling_point: 77.355,
    melting_point: 63.15,
    density: 1.251,
    summary: "Nitrogen is a chemical element with symbol N and atomic number 7. It was first discovered and isolated by Scottish physician Daniel Rutherford in 1772.",
    electron_configuration: "[He] 2s2 2p3",
    cpk_hex: "3050f8"
  },
  {
    number: 8,
    symbol: "O",
    name: "Oxygen",
    atomic_mass: 15.999,
    category: "diatomic nonmetal",
    group: 16,
    period: 2,
    phase: "Gas",
    appearance: null,
    boiling_point: 90.188,
    melting_point: 54.36,
    density: 1.429,
    summary: "Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group on the periodic table, a highly reactive nonmetal, and an oxidizing agent that readily forms oxides with most elements as well as with other compounds.",
    electron_configuration: "[He] 2s2 2p4",
    cpk_hex: "ff0d0d"
  },
  {
    number: 9,
    symbol: "F",
    name: "Fluorine",
    atomic_mass: 18.998,
    category: "diatomic nonmetal",
    group: 17,
    period: 2,
    phase: "Gas",
    appearance: "pale yellow gas",
    boiling_point: 85.03,
    melting_point: 53.48,
    density: 1.696,
    summary: "Fluorine is a chemical element with symbol F and atomic number 9. It is the most electronegative element and is extremely reactive: almost all other elements, including some noble gases, form compounds with fluorine.",
    electron_configuration: "[He] 2s2 2p5",
    cpk_hex: "90e050"
  },
  {
    number: 10,
    symbol: "Ne",
    name: "Neon",
    atomic_mass: 20.18,
    category: "noble gas",
    group: 18,
    period: 2,
    phase: "Gas",
    appearance: "colorless gas exhibiting an orange-red glow when placed in a high voltage electric field",
    boiling_point: 27.104,
    melting_point: 24.56,
    density: 0.9002,
    summary: "Neon is a chemical element with symbol Ne and atomic number 10. It is a noble gas. Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air.",
    electron_configuration: "[He] 2s2 2p6",
    cpk_hex: "b3e3f5"
  },
  {
    number: 11,
    symbol: "Na",
    name: "Sodium",
    atomic_mass: 22.99,
    category: "alkali metal",
    group: 1,
    period: 3,
    phase: "Solid",
    appearance: "silvery white metallic",
    boiling_point: 1156,
    melting_point: 370.944,
    density: 0.968,
    summary: "Sodium is a chemical element with symbol Na and atomic number 11. It is a soft, silvery-white, highly reactive metal.",
    electron_configuration: "[Ne] 3s1",
    cpk_hex: "ab5cf2"
  },
  {
    number: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomic_mass: 24.305,
    category: "alkaline earth metal",
    group: 2,
    period: 3,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 1363,
    melting_point: 923,
    density: 1.738,
    summary: "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column (group 2, or alkaline earth metals) of the periodic table.",
    electron_configuration: "[Ne] 3s2",
    cpk_hex: "8aff00"
  },
  {
    number: 13,
    symbol: "Al",
    name: "Aluminium",
    atomic_mass: 26.982,
    category: "post-transition metal",
    group: 13,
    period: 3,
    phase: "Solid",
    appearance: "silvery gray metallic",
    boiling_point: 2743,
    melting_point: 933.47,
    density: 2.7,
    summary: "Aluminium is a chemical element in the boron group with symbol Al and atomic number 13. It is a silvery-white, soft, nonmagnetic, ductile metal.",
    electron_configuration: "[Ne] 3s2 3p1",
    cpk_hex: "bfa6a6"
  },
  {
    number: 14,
    symbol: "Si",
    name: "Silicon",
    atomic_mass: 28.085,
    category: "metalloid",
    group: 14,
    period: 3,
    phase: "Solid",
    appearance: "crystalline, reflective with a bluish-tinge",
    boiling_point: 3538,
    melting_point: 1687,
    density: 2.329,
    summary: "Silicon is a chemical element with symbol Si and atomic number 14. It is a hard and brittle crystalline solid with a blue-grey metallic lustre; and it is a tetravalent metalloid and semiconductor.",
    electron_configuration: "[Ne] 3s2 3p2",
    cpk_hex: "f0c8a0"
  },
  {
    number: 15,
    symbol: "P",
    name: "Phosphorus",
    atomic_mass: 30.974,
    category: "polyatomic nonmetal",
    group: 15,
    period: 3,
    phase: "Solid",
    appearance: "colourless, waxy white, yellow, scarlet, red, violet, black",
    boiling_point: 550.5,
    melting_point: 317.3,
    density: 1.823,
    summary: "Phosphorus is a chemical element with symbol P and atomic number 15. As an element, phosphorus exists in two major forms—white phosphorus and red phosphorus—but because it is highly reactive, phosphorus is never found as a free element on Earth.",
    electron_configuration: "[Ne] 3s2 3p3",
    cpk_hex: "ff8000"
  },
  {
    number: 16,
    symbol: "S",
    name: "Sulfur",
    atomic_mass: 32.06,
    category: "polyatomic nonmetal",
    group: 16,
    period: 3,
    phase: "Solid",
    appearance: "lemon yellow sintered microcrystals",
    boiling_point: 717.8,
    melting_point: 388.36,
    density: 2.07,
    summary: "Sulfur is a chemical element with symbol S and atomic number 16. It is abundant, multivalent, and nonmetallic. Under normal conditions, sulfur atoms form cyclic octatomic molecules with a chemical formula S8.",
    electron_configuration: "[Ne] 3s2 3p4",
    cpk_hex: "ffff30"
  },
  {
    number: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomic_mass: 35.45,
    category: "diatomic nonmetal",
    group: 17,
    period: 3,
    phase: "Gas",
    appearance: "pale yellow-green gas",
    boiling_point: 239.11,
    melting_point: 171.6,
    density: 3.214,
    summary: "Chlorine is a chemical element with symbol Cl and atomic number 17. It also has a relative atomic mass of 35.5; which is derived from the stable isotopes 35Cl and 37Cl.",
    electron_configuration: "[Ne] 3s2 3p5",
    cpk_hex: "1ff01f"
  },
  {
    number: 18,
    symbol: "Ar",
    name: "Argon",
    atomic_mass: 39.948,
    category: "noble gas",
    group: 18,
    period: 3,
    phase: "Gas",
    appearance: "colorless gas exhibiting a lilac/violet glow when placed in a high voltage electric field",
    boiling_point: 87.302,
    melting_point: 83.81,
    density: 1.784,
    summary: "Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas. Argon is the third-most abundant gas in the Earth's atmosphere, at 0.934% (9340 ppmv).",
    electron_configuration: "[Ne] 3s2 3p6",
    cpk_hex: "80d1ff"
  },
  {
    number: 19,
    symbol: "K",
    name: "Potassium",
    atomic_mass: 39.098,
    category: "alkali metal",
    group: 1,
    period: 4,
    phase: "Solid",
    appearance: "silvery gray",
    boiling_point: 1032,
    melting_point: 336.7,
    density: 0.862,
    summary: "Potassium is a chemical element with symbol K and atomic number 19. It was first isolated from potash, the ashes of plants, from which its name derives. In the Periodic table, potassium is one of the alkali metals.",
    electron_configuration: "[Ar] 4s1",
    cpk_hex: "8f40d4"
  },
  {
    number: 20,
    symbol: "Ca",
    name: "Calcium",
    atomic_mass: 40.078,
    category: "alkaline earth metal",
    group: 2,
    period: 4,
    phase: "Solid",
    appearance: null,
    boiling_point: 1757,
    melting_point: 1115,
    density: 1.54,
    summary: "Calcium is a chemical element with symbol Ca and atomic number 20. Calcium is a soft gray alkaline earth metal, fourth-most abundant element by mass in the Earth's crust.",
    electron_configuration: "[Ar] 4s2",
    cpk_hex: "3dff00"
  },
  {
    number: 21,
    symbol: "Sc",
    name: "Scandium",
    atomic_mass: 44.956,
    category: "transition metal",
    group: 3,
    period: 4,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 3109,
    melting_point: 1814,
    density: 2.985,
    summary: "Scandium is a chemical element with symbol Sc and atomic number 21. A silvery-white metallic d-block element, it has historically been sometimes classified as a rare earth element, together with yttrium and the lanthanides.",
    electron_configuration: "[Ar] 3d1 4s2",
    cpk_hex: "e6e6e6"
  },
  {
    number: 22,
    symbol: "Ti",
    name: "Titanium",
    atomic_mass: 47.867,
    category: "transition metal",
    group: 4,
    period: 4,
    phase: "Solid",
    appearance: "silvery grey-white metallic",
    boiling_point: 3560,
    melting_point: 1941,
    density: 4.506,
    summary: "Titanium is a chemical element with symbol Ti and atomic number 22. It is a lustrous transition metal with a silver color, low density, and high strength. Titanium is resistant to corrosion in sea water, aqua regia, and chlorine.",
    electron_configuration: "[Ar] 3d2 4s2",
    cpk_hex: "bfc2c7"
  },
  {
    number: 23,
    symbol: "V",
    name: "Vanadium",
    atomic_mass: 50.942,
    category: "transition metal",
    group: 5,
    period: 4,
    phase: "Solid",
    appearance: "blue-silver-grey metal",
    boiling_point: 3680,
    melting_point: 2183,
    density: 6.11,
    summary: "Vanadium is a chemical element with symbol V and atomic number 23. It is a hard, silvery-grey, ductile, malleable transition metal. The elemental metal is rarely found in nature, but once isolated artificially, the formation of an oxide layer (passivation) somewhat stabilizes the free metal against further oxidation.",
    electron_configuration: "[Ar] 3d3 4s2",
    cpk_hex: "a6a6ab"
  },
  {
    number: 24,
    symbol: "Cr",
    name: "Chromium",
    atomic_mass: 51.996,
    category: "transition metal",
    group: 6,
    period: 4,
    phase: "Solid",
    appearance: "silvery metallic",
    boiling_point: 2944,
    melting_point: 2180,
    density: 7.19,
    summary: "Chromium is a chemical element with symbol Cr and atomic number 24. It is the first element in group 6. It is a steely-grey, lustrous, hard and brittle transition metal.",
    electron_configuration: "[Ar] 3d5 4s1",
    cpk_hex: "8a99c7"
  },
  {
    number: 25,
    symbol: "Mn",
    name: "Manganese",
    atomic_mass: 54.938,
    category: "transition metal",
    group: 7,
    period: 4,
    phase: "Solid",
    appearance: "silvery metallic",
    boiling_point: 2334,
    melting_point: 1519,
    density: 7.21,
    summary: "Manganese is a chemical element with symbol Mn and atomic number 25. It is not found as a free element in nature; it is often found in minerals in combination with iron. Manganese is a transition metal with a multifaceted array of industrial alloy uses, particularly in stainless steels.",
    electron_configuration: "[Ar] 3d5 4s2",
    cpk_hex: "9c7ac7"
  },
  {
    number: 26,
    symbol: "Fe",
    name: "Iron",
    atomic_mass: 55.845,
    category: "transition metal",
    group: 8,
    period: 4,
    phase: "Solid",
    appearance: "lustrous metallic with a grayish tinge",
    boiling_point: 3134,
    melting_point: 1811,
    density: 7.874,
    summary: "Iron is a chemical element with symbol Fe and atomic number 26. It is a metal that belongs to the first transition series and group 8 of the periodic table.",
    electron_configuration: "[Ar] 3d6 4s2",
    cpk_hex: "e06633"
  },
  {
    number: 27,
    symbol: "Co",
    name: "Cobalt",
    atomic_mass: 58.933,
    category: "transition metal",
    group: 9,
    period: 4,
    phase: "Solid",
    appearance: "lustrous metallic with a grayish tinge",
    boiling_point: 3200,
    melting_point: 1768,
    density: 8.9,
    summary: "Cobalt is a chemical element with symbol Co and atomic number 27. Like iron, cobalt is found in the Earth's crust only in chemically combined form, save for small deposits found in alloys of natural meteoric iron.",
    electron_configuration: "[Ar] 3d7 4s2",
    cpk_hex: "f090a0"
  },
  {
    number: 28,
    symbol: "Ni",
    name: "Nickel",
    atomic_mass: 58.693,
    category: "transition metal",
    group: 10,
    period: 4,
    phase: "Solid",
    appearance: "lustrous, metallic and silver with a gold tinge",
    boiling_point: 3003,
    melting_point: 1728,
    density: 8.908,
    summary: "Nickel is a chemical element with symbol Ni and atomic number 28. It is a silvery-white lustrous metal with a slight golden tinge. Nickel belongs to the transition metals and is hard and ductile.",
    electron_configuration: "[Ar] 3d8 4s2",
    cpk_hex: "50d050"
  },
  {
    number: 29,
    symbol: "Cu",
    name: "Copper",
    atomic_mass: 63.546,
    category: "transition metal",
    group: 11,
    period: 4,
    phase: "Solid",
    appearance: "red-orange metallic luster",
    boiling_point: 2835,
    melting_point: 1357.77,
    density: 8.96,
    summary: "Copper is a chemical element with symbol Cu and atomic number 29. It is a soft, malleable, and ductile metal with very high thermal and electrical conductivity.",
    electron_configuration: "[Ar] 3d10 4s1",
    cpk_hex: "c88033"
  },
  {
    number: 30,
    symbol: "Zn",
    name: "Zinc",
    atomic_mass: 65.38,
    category: "transition metal",
    group: 12,
    period: 4,
    phase: "Solid",
    appearance: "silver-gray",
    boiling_point: 1180,
    melting_point: 692.68,
    density: 7.14,
    summary: "Zinc is a chemical element with symbol Zn and atomic number 30. It is the first element in group 12 of the periodic table. In some respects zinc is chemically similar to magnesium: both elements exhibit only one normal oxidation state (+2).",
    electron_configuration: "[Ar] 3d10 4s2",
    cpk_hex: "7d80b0"
  },
  {
    number: 31,
    symbol: "Ga",
    name: "Gallium",
    atomic_mass: 69.723,
    category: "post-transition metal",
    group: 13,
    period: 4,
    phase: "Solid",
    appearance: "silver-white",
    boiling_point: 2673,
    melting_point: 302.91,
    density: 5.91,
    summary: "Gallium is a chemical element with symbol Ga and atomic number 31. Elemental gallium is a soft, silvery blue metal at standard temperature and pressure; however in its liquid state it becomes silvery white.",
    electron_configuration: "[Ar] 3d10 4s2 4p1",
    cpk_hex: "c28f8f"
  },
  {
    number: 32,
    symbol: "Ge",
    name: "Germanium",
    atomic_mass: 72.63,
    category: "metalloid",
    group: 14,
    period: 4,
    phase: "Solid",
    appearance: "grayish-white",
    boiling_point: 3106,
    melting_point: 1211.4,
    density: 5.323,
    summary: "Germanium is a chemical element with symbol Ge and atomic number 32. It is a lustrous, hard, grayish-white metalloid in the carbon group, chemically similar to its group neighbors tin and silicon.",
    electron_configuration: "[Ar] 3d10 4s2 4p2",
    cpk_hex: "668f8f"
  },
  {
    number: 33,
    symbol: "As",
    name: "Arsenic",
    atomic_mass: 74.922,
    category: "metalloid",
    group: 15,
    period: 4,
    phase: "Solid",
    appearance: "metallic grey",
    boiling_point: null,
    melting_point: 1090,
    density: 5.727,
    summary: "Arsenic is a chemical element with symbol As and atomic number 33. Arsenic occurs in many minerals, usually in combination with sulfur and metals, but also as a pure elemental crystal. Arsenic is a metalloid.",
    electron_configuration: "[Ar] 3d10 4s2 4p3",
    cpk_hex: "bd80e3"
  },
  {
    number: 34,
    symbol: "Se",
    name: "Selenium",
    atomic_mass: 78.971,
    category: "polyatomic nonmetal",
    group: 16,
    period: 4,
    phase: "Solid",
    appearance: "black, red, and gray (notably) allotropes",
    boiling_point: 958,
    melting_point: 494,
    density: 4.81,
    summary: "Selenium is a chemical element with symbol Se and atomic number 34. It is a nonmetal with properties that are intermediate between the elements above and below in the periodic table, sulfur and tellurium, and also has similarities to arsenic.",
    electron_configuration: "[Ar] 3d10 4s2 4p4",
    cpk_hex: "ffa100"
  },
  {
    number: 35,
    symbol: "Br",
    name: "Bromine",
    atomic_mass: 79.904,
    category: "diatomic nonmetal",
    group: 17,
    period: 4,
    phase: "Liquid",
    appearance: "red-brown liquid",
    boiling_point: 332,
    melting_point: 265.8,
    density: 3.1028,
    summary: "Bromine is a chemical element with symbol Br and atomic number 35. It is the third-lightest halogen, and is a fuming red-brown liquid at room temperature that evaporates readily to form a similarly coloured gas.",
    electron_configuration: "[Ar] 3d10 4s2 4p5",
    cpk_hex: "a62929"
  },
  {
    number: 36,
    symbol: "Kr",
    name: "Krypton",
    atomic_mass: 83.798,
    category: "noble gas",
    group: 18,
    period: 4,
    phase: "Gas",
    appearance: "colorless gas, exhibiting a whitish glow in a high electric field",
    boiling_point: 119.93,
    melting_point: 115.78,
    density: 3.749,
    summary: "Krypton is a chemical element with symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements. A colorless, odorless, tasteless noble gas, krypton occurs in trace amounts in the atmosphere and is often used with other rare gases in fluorescent lamps.",
    electron_configuration: "[Ar] 3d10 4s2 4p6",
    cpk_hex: "5cb8d1"
  },
  {
    number: 47,
    symbol: "Ag",
    name: "Silver",
    atomic_mass: 107.87,
    category: "transition metal",
    group: 11,
    period: 5,
    phase: "Solid",
    appearance: "lustrous white metal",
    boiling_point: 2435,
    melting_point: 1234.93,
    density: 10.49,
    summary: "Silver is a chemical element with symbol Ag and atomic number 47. A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal.",
    electron_configuration: "[Kr] 4d10 5s1",
    cpk_hex: "c0c0c0"
  },
  {
    number: 79,
    symbol: "Au",
    name: "Gold",
    atomic_mass: 196.97,
    category: "transition metal",
    group: 11,
    period: 6,
    phase: "Solid",
    appearance: "metallic yellow",
    boiling_point: 3109,
    melting_point: 1337.33,
    density: 19.3,
    summary: "Gold is a chemical element with symbol Au and atomic number 79. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal. Chemically, gold is a transition metal.",
    electron_configuration: "[Xe] 4f14 5d10 6s1",
    cpk_hex: "ffd123"
  },
  {
    number: 80,
    symbol: "Hg",
    name: "Mercury",
    atomic_mass: 200.59,
    category: "transition metal",
    group: 12,
    period: 6,
    phase: "Liquid",
    appearance: "silvery",
    boiling_point: 629.88,
    melting_point: 234.321,
    density: 13.534,
    summary: "Mercury is a chemical element with symbol Hg and atomic number 80. It is commonly known as quicksilver and was formerly named hydrargyrum. A heavy, silvery d-block element, mercury is the only metallic element that is liquid at standard conditions for temperature and pressure.",
    electron_configuration: "[Xe] 4f14 5d10 6s2",
    cpk_hex: "b8b8d0"
  },
  {
    number: 58,
    symbol: "Ce",
    name: "Cerium",
    atomic_mass: 140.12,
    category: "lanthanide",
    group: 3,
    period: 8,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 3716,
    melting_point: 1068,
    density: 6.77,
    summary: "Cerium is a chemical element with symbol Ce and atomic number 58. Cerium is a soft, ductile, and silvery-white metal that tarnishes when exposed to air, and it is soft enough to be cut with a knife.",
    electron_configuration: "[Xe] 4f1 5d1 6s2",
    cpk_hex: "ffffc7"
  },
  {
    number: 90,
    symbol: "Th",
    name: "Thorium",
    atomic_mass: 232.04,
    category: "actinide",
    group: 3,
    period: 9,
    phase: "Solid",
    appearance: "silvery, tarnishing black",
    boiling_point: 5061,
    melting_point: 2023,
    density: 11.7,
    summary: "Thorium is a weakly radioactive metallic chemical element with symbol Th and atomic number 90. Thorium is silvery and tarnishes black when exposed to air, forming thorium dioxide; it is moderately soft, malleable, and has a high melting point.",
    electron_configuration: "[Rn] 6d2 7s2",
    cpk_hex: "00ba00"
  },
  {
    number: 37,
    symbol: "Rb",
    name: "Rubidium",
    atomic_mass: 85.468,
    category: "alkali metal",
    group: 1,
    period: 5,
    phase: "Solid",
    appearance: "grey white",
    boiling_point: 961,
    melting_point: 312.45,
    density: 1.532,
    summary: "Rubidium is the chemical element with the symbol Rb and atomic number 37. Rubidium is a soft, silvery-white metallic element of the alkali metal group.",
    electron_configuration: "[Kr] 5s1",
    cpk_hex: "702eb0"
  },
  {
    number: 38,
    symbol: "Sr",
    name: "Strontium",
    atomic_mass: 87.62,
    category: "alkaline earth metal",
    group: 2,
    period: 5,
    phase: "Solid",
    appearance: null,
    boiling_point: 1650,
    melting_point: 1050,
    density: 2.64,
    summary: "Strontium is a chemical element with symbol Sr and atomic number 38. An alkaline earth metal, strontium is a soft silver-white yellowish metallic element that is highly chemically reactive.",
    electron_configuration: "[Kr] 5s2",
    cpk_hex: "00ff00"
  },
  {
    number: 82,
    symbol: "Pb",
    name: "Lead",
    atomic_mass: 207.2,
    category: "post-transition metal",
    group: 14,
    period: 6,
    phase: "Solid",
    appearance: "metallic gray",
    boiling_point: 2022,
    melting_point: 600.61,
    density: 11.34,
    summary: "Lead is a chemical element with symbol Pb and atomic number 82. It is a heavy metal that is denser than most common materials. Lead is soft and malleable, and also has a relatively low melting point.",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p2",
    cpk_hex: "575961"
  },
  {
    number: 92,
    symbol: "U",
    name: "Uranium",
    atomic_mass: 238.03,
    category: "actinide",
    group: 3,
    period: 9,
    phase: "Solid",
    appearance: null,
    boiling_point: 4404,
    melting_point: 1405.3,
    density: 19.1,
    summary: "Uranium is a chemical element with symbol U and atomic number 92. It is a silvery-grey metal in the actinide series of the periodic table. A uranium atom has 92 protons and 92 electrons, of which 6 are valence electrons.",
    electron_configuration: "[Rn] 5f3 6d1 7s2",
    cpk_hex: "00a100"
  },
  {
    number: 39,
    symbol: "Y",
    name: "Yttrium",
    atomic_mass: 88.906,
    category: "transition metal",
    group: 3,
    period: 5,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 3609,
    melting_point: 1799,
    density: 4.472,
    summary: "Yttrium is a chemical element with symbol Y and atomic number 39. It is a silvery-metallic transition metal chemically similar to the lanthanides and it has often been classified as a \"rare earth element\".",
    electron_configuration: "[Kr] 4d1 5s2",
    cpk_hex: "94ffff"
  },
  {
    number: 40,
    symbol: "Zr",
    name: "Zirconium",
    atomic_mass: 91.224,
    category: "transition metal",
    group: 4,
    period: 5,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 4650,
    melting_point: 2128,
    density: 6.52,
    summary: "Zirconium is a chemical element with symbol Zr and atomic number 40. The name of zirconium is taken from the name of the mineral zircon, the most important source of zirconium. It is a lustrous, grey-white, strong transition metal that resembles hafnium and, to a lesser extent, titanium.",
    electron_configuration: "[Kr] 4d2 5s2",
    cpk_hex: "94e0e0"
  },
  {
    number: 41,
    symbol: "Nb",
    name: "Niobium",
    atomic_mass: 92.906,
    category: "transition metal",
    group: 5,
    period: 5,
    phase: "Solid",
    appearance: "gray metallic, bluish when oxidized",
    boiling_point: 5017,
    melting_point: 2750,
    density: 8.57,
    summary: "Niobium, formerly columbium, is a chemical element with symbol Nb and atomic number 41. It is a soft, grey, ductile transition metal, which is often found in the pyrochlore mineral, the main commercial source for niobium, and columbite.",
    electron_configuration: "[Kr] 4d4 5s1",
    cpk_hex: "73c2c2"
  },
  {
    number: 42,
    symbol: "Mo",
    name: "Molybdenum",
    atomic_mass: 95.95,
    category: "transition metal",
    group: 6,
    period: 5,
    phase: "Solid",
    appearance: "gray metallic",
    boiling_point: 4912,
    melting_point: 2896,
    density: 10.28,
    summary: "Molybdenum is a chemical element with symbol Mo and atomic number 42. The name is from Neo-Latin molybdaenum, from Ancient Greek Μόλυβδος molybdos, meaning lead, since its ores were confused with lead ores.",
    electron_configuration: "[Kr] 4d5 5s1",
    cpk_hex: "54b5b5"
  },
  {
    number: 43,
    symbol: "Tc",
    name: "Technetium",
    atomic_mass: 98,
    category: "transition metal",
    group: 7,
    period: 5,
    phase: "Solid",
    appearance: "shiny gray metal",
    boiling_point: 4538,
    melting_point: 2430,
    density: 11,
    summary: "Technetium is a chemical element with symbol Tc and atomic number 43. It is the element with the lowest atomic number in the periodic table that has no stable isotopes: every form of it is radioactive. Nearly all technetium is produced synthetically, and only minute amounts are found in nature.",
    electron_configuration: "[Kr] 4d5 5s2",
    cpk_hex: "3b9e9e"
  },
  {
    number: 44,
    symbol: "Ru",
    name: "Ruthenium",
    atomic_mass: 101.07,
    category: "transition metal",
    group: 8,
    period: 5,
    phase: "Solid",
    appearance: "silvery white metallic",
    boiling_point: 4423,
    melting_point: 2606,
    density: 12.45,
    summary: "Ruthenium is a chemical element with symbol Ru and atomic number 44. It is a rare transition metal belonging to the platinum group of the periodic table. Like the other metals of the platinum group, ruthenium is inert to most other chemicals.",
    electron_configuration: "[Kr] 4d7 5s1",
    cpk_hex: "248f8f"
  },
  {
    number: 45,
    symbol: "Rh",
    name: "Rhodium",
    atomic_mass: 102.91,
    category: "transition metal",
    group: 9,
    period: 5,
    phase: "Solid",
    appearance: "silvery white metallic",
    boiling_point: 3968,
    melting_point: 2237,
    density: 12.41,
    summary: "Rhodium is a chemical element with symbol Rh and atomic number 45. It is a rare, silvery-white, hard, and chemically inert transition metal. It is a member of the platinum group.",
    electron_configuration: "[Kr] 4d8 5s1",
    cpk_hex: "0a7d8c"
  },
  {
    number: 46,
    symbol: "Pd",
    name: "Palladium",
    atomic_mass: 106.42,
    category: "transition metal",
    group: 10,
    period: 5,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 3236,
    melting_point: 1828.05,
    density: 12.023,
    summary: "Palladium is a chemical element with symbol Pd and atomic number 46. It is a rare and lustrous silvery-white metal discovered in 1803 by William Hyde Wollaston. He named it after the asteroid Pallas, which was itself named after the epithet of the Greek goddess Athena, acquired by her when she slew Pallas.",
    electron_configuration: "[Kr] 4d10",
    cpk_hex: "006985"
  },
  {
    number: 48,
    symbol: "Cd",
    name: "Cadmium",
    atomic_mass: 112.41,
    category: "transition metal",
    group: 12,
    period: 5,
    phase: "Solid",
    appearance: "silvery bluish-gray metallic",
    boiling_point: 1040,
    melting_point: 594.22,
    density: 8.65,
    summary: "Cadmium is a chemical element with symbol Cd and atomic number 48. This soft, bluish-white metal is chemically similar to the two other stable metals in group 12, zinc and mercury.",
    electron_configuration: "[Kr] 4d10 5s2",
    cpk_hex: "ffd98f"
  },
  {
    number: 49,
    symbol: "In",
    name: "Indium",
    atomic_mass: 114.82,
    category: "post-transition metal",
    group: 13,
    period: 5,
    phase: "Solid",
    appearance: "silvery lustrous gray",
    boiling_point: 2345,
    melting_point: 429.7485,
    density: 7.31,
    summary: "Indium is a chemical element with symbol In and atomic number 49. It is a post-transition metallic element that is rare in Earth's crust. The metal is very soft, malleable and easily fusible, with a melting point higher than sodium, but lower than lithium or tin.",
    electron_configuration: "[Kr] 4d10 5s2 5p1",
    cpk_hex: "a67573"
  },
  {
    number: 50,
    symbol: "Sn",
    name: "Tin",
    atomic_mass: 118.71,
    category: "post-transition metal",
    group: 14,
    period: 5,
    phase: "Solid",
    appearance: "silvery-white (beta, white tin); gray (alpha, gray tin)",
    boiling_point: 2875,
    melting_point: 505.08,
    density: 7.265,
    summary: "Tin is a chemical element with the symbol Sn and atomic number 50. It is a main group metal in group 14 of the periodic table. Tin shows a chemical similarity to both neighboring group-14 elements, germanium and lead, and has two main oxidation states, +2 and the slightly more stable +4.",
    electron_configuration: "[Kr] 4d10 5s2 5p2",
    cpk_hex: "668080"
  },
  {
    number: 51,
    symbol: "Sb",
    name: "Antimony",
    atomic_mass: 121.76,
    category: "metalloid",
    group: 15,
    period: 5,
    phase: "Solid",
    appearance: "silvery lustrous gray",
    boiling_point: 1860,
    melting_point: 903.78,
    density: 6.697,
    summary: "Antimony is a chemical element with symbol Sb and atomic number 51. A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite (Sb2S3). Antimony compounds have been known since ancient times and were used for cosmetics; metallic antimony was also known, but it was erroneously identified as lead upon its discovery.",
    electron_configuration: "[Kr] 4d10 5s2 5p3",
    cpk_hex: "9e63b5"
  },
  {
    number: 52,
    symbol: "Te",
    name: "Tellurium",
    atomic_mass: 127.60,
    category: "metalloid",
    group: 16,
    period: 5,
    phase: "Solid",
    appearance: null,
    boiling_point: 1261,
    melting_point: 722.66,
    density: 6.24,
    summary: "Tellurium is a chemical element with symbol Te and atomic number 52. It is a brittle, mildly toxic, rare, silver-white metalloid. Tellurium is chemically related to selenium and sulfur.",
    electron_configuration: "[Kr] 4d10 5s2 5p4",
    cpk_hex: "d47a00"
  },
  {
    number: 57,
    symbol: "La",
    name: "Lanthanum",
    atomic_mass: 138.91,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 3737,
    melting_point: 1193,
    density: 6.162,
    summary: "Lanthanum is a soft, ductile, silvery-white metallic chemical element with symbol La and atomic number 57. It tarnishes rapidly when exposed to air and is soft enough to be cut with a knife.",
    electron_configuration: "[Xe] 5d1 6s2",
    cpk_hex: "70d4ff"
  },
  {
    number: 59,
    symbol: "Pr",
    name: "Praseodymium",
    atomic_mass: 140.91,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    appearance: "grayish white",
    boiling_point: 3403,
    melting_point: 1208,
    density: 6.77,
    summary: "Praseodymium is a chemical element with symbol Pr and atomic number 59. Praseodymium is a soft, silvery, malleable and ductile metal in the lanthanide group. It is valued for its magnetic, electrical, chemical, and optical properties.",
    electron_configuration: "[Xe] 4f3 6s2",
    cpk_hex: "d9ffc7"
  },
  {
    number: 60,
    symbol: "Nd",
    name: "Neodymium",
    atomic_mass: 144.24,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 3347,
    melting_point: 1297,
    density: 7.01,
    summary: "Neodymium is a chemical element with symbol Nd and atomic number 60. It is a soft silvery metal that tarnishes in air. Neodymium was discovered in 1885 by the Austrian chemist Carl Auer von Welsbach.",
    electron_configuration: "[Xe] 4f4 6s2",
    cpk_hex: "c7ffc7"
  },
  {
    number: 61,
    symbol: "Pm",
    name: "Promethium",
    atomic_mass: 145,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    appearance: "metallic",
    boiling_point: 3273,
    melting_point: 1315,
    density: 7.26,
    summary: "Promethium, originally prometheum, is a chemical element with the symbol Pm and atomic number 61. All of its isotopes are radioactive; it is extremely rare, with only about 500-600 grams naturally occurring in Earth's crust at any given time.",
    electron_configuration: "[Xe] 4f5 6s2",
    cpk_hex: "a3ffc7"
  },
  {
    number: 62,
    symbol: "Sm",
    name: "Samarium",
    atomic_mass: 150.36,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 2067,
    melting_point: 1345,
    density: 7.52,
    summary: "Samarium is a chemical element with symbol Sm and atomic number 62. It is a moderately hard silvery metal that readily oxidizes in air. Being a typical member of the lanthanide series, samarium usually possesses the oxidation state +3.",
    electron_configuration: "[Xe] 4f6 6s2",
    cpk_hex: "8fffc7"
  },
  {
    number: 63,
    symbol: "Eu",
    name: "Europium",
    atomic_mass: 151.96,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    appearance: null,
    boiling_point: 1802,
    melting_point: 1099,
    density: 5.264,
    summary: "Europium is a chemical element with symbol Eu and atomic number 63. It was isolated in 1901 and is named after the continent of Europe. It is a moderately hard, silvery metal which readily oxidizes in air and water.",
    electron_configuration: "[Xe] 4f7 6s2",
    cpk_hex: "61ffc7"
  },
  {
    number: 64,
    symbol: "Gd",
    name: "Gadolinium",
    atomic_mass: 157.25,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 3546,
    melting_point: 1585,
    density: 7.9,
    summary: "Gadolinium is a chemical element with symbol Gd and atomic number 64. It is a silvery-white, malleable and ductile rare-earth metal. It is found in nature only in combined (salt) form.",
    electron_configuration: "[Xe] 4f7 5d1 6s2",
    cpk_hex: "45ffc7"
  },
  {
    number: 65,
    symbol: "Tb",
    name: "Terbium",
    atomic_mass: 158.93,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 3503,
    melting_point: 1629,
    density: 8.23,
    summary: "Terbium is a chemical element with symbol Tb and atomic number 65. It is a silvery-white, rare earth metal that is malleable, ductile and soft enough to be cut with a knife. Terbium is never found in nature as a free element, but it is contained in many minerals, including cerite, gadolinite, monazite, xenotime and euxenite.",
    electron_configuration: "[Xe] 4f9 6s2",
    cpk_hex: "30ffc7"
  },
  {
    number: 66,
    symbol: "Dy",
    name: "Dysprosium",
    atomic_mass: 162.50,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 2840,
    melting_point: 1680,
    density: 8.54,
    summary: "Dysprosium is a chemical element with the symbol Dy and atomic number 66. It is a rare earth element with a metallic silver luster. Dysprosium is never found in nature as a free element, though it is found in various minerals, such as xenotime.",
    electron_configuration: "[Xe] 4f10 6s2",
    cpk_hex: "1fffc7"
  },
  {
    number: 67,
    symbol: "Ho",
    name: "Holmium",
    atomic_mass: 164.93,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 2993,
    melting_point: 1734,
    density: 8.79,
    summary: "Holmium is a chemical element with symbol Ho and atomic number 67. Part of the lanthanide series, holmium is a rare-earth element. Holmium was discovered by Swedish chemist Per Teodor Cleve.",
    electron_configuration: "[Xe] 4f11 6s2",
    cpk_hex: "00ff9c"
  },
  {
    number: 68,
    symbol: "Er",
    name: "Erbium",
    atomic_mass: 167.26,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 3141,
    melting_point: 1802,
    density: 9.066,
    summary: "Erbium is a chemical element in the lanthanide series, with symbol Er and atomic number 68. A silvery-white solid metal when artificially isolated, natural erbium is always found in chemical combination with other elements on Earth. As such, it is a rare earth element.",
    electron_configuration: "[Xe] 4f12 6s2",
    cpk_hex: "00e675"
  },
  {
    number: 69,
    symbol: "Tm",
    name: "Thulium",
    atomic_mass: 168.93,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    appearance: "silvery gray",
    boiling_point: 2223,
    melting_point: 1818,
    density: 9.32,
    summary: "Thulium is a chemical element with symbol Tm and atomic number 69. It is the thirteenth and third-last element in the lanthanide series. Like the other lanthanides, the most common oxidation state is +3, seen in its oxide, halides and other compounds.",
    electron_configuration: "[Xe] 4f13 6s2",
    cpk_hex: "00d452"
  },
  {
    number: 70,
    symbol: "Yb",
    name: "Ytterbium",
    atomic_mass: 173.05,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    appearance: null,
    boiling_point: 1469,
    melting_point: 1097,
    density: 6.9,
    summary: "Ytterbium is a chemical element with symbol Yb and atomic number 70. It is the fourteenth and penultimate element in the lanthanide series, which is the basis of the relative stability of its +2 oxidation state. However, like the other lanthanides, its most common oxidation state is +3, as in its oxide, halides and other compounds.",
    electron_configuration: "[Xe] 4f14 6s2",
    cpk_hex: "00bf38"
  },
  {
    number: 71,
    symbol: "Lu",
    name: "Lutetium",
    atomic_mass: 174.97,
    category: "lanthanide",
    group: 3,
    period: 6,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 3675,
    melting_point: 1925,
    density: 9.841,
    summary: "Lutetium is a chemical element with symbol Lu and atomic number 71. It is a silvery white metal, which resists corrosion in dry air, but not in moist air. Lutetium is the last element in the lanthanide series, and it is traditionally counted among the rare earth elements.",
    electron_configuration: "[Xe] 4f14 5d1 6s2",
    cpk_hex: "00ab24"
  },
  {
    number: 72,
    symbol: "Hf",
    name: "Hafnium",
    atomic_mass: 178.49,
    category: "transition metal",
    group: 4,
    period: 6,
    phase: "Solid",
    appearance: "steel gray",
    boiling_point: 4876,
    melting_point: 2506,
    density: 13.31,
    summary: "Hafnium is a chemical element with symbol Hf and atomic number 72. A lustrous, silvery gray, tetravalent transition metal, hafnium chemically resembles zirconium and is found in many zirconium minerals. Its existence was predicted by Dmitri Mendeleev in 1869, though it was not identified until 1923, making it the penultimate stable element to be discovered.",
    electron_configuration: "[Xe] 4f14 5d2 6s2",
    cpk_hex: "4dc2ff"
  },
  {
    number: 73,
    symbol: "Ta",
    name: "Tantalum",
    atomic_mass: 180.95,
    category: "transition metal",
    group: 5,
    period: 6,
    phase: "Solid",
    appearance: "gray blue",
    boiling_point: 5731,
    melting_point: 3290,
    density: 16.69,
    summary: "Tantalum is a chemical element with symbol Ta and atomic number 73. Previously known as tantalium, its name comes from Tantalus, a Greek mythological figure. Tantalum is a rare, hard, blue-gray, lustrous transition metal that is highly corrosion-resistant.",
    electron_configuration: "[Xe] 4f14 5d3 6s2",
    cpk_hex: "4da6ff"
  },
  {
    number: 75,
    symbol: "Re",
    name: "Rhenium",
    atomic_mass: 186.21,
    category: "transition metal",
    group: 7,
    period: 6,
    phase: "Solid",
    appearance: "silvery-grayish",
    boiling_point: 5869,
    melting_point: 3459,
    density: 21.02,
    summary: "Rhenium is a chemical element with symbol Re and atomic number 75. It is a silvery-white, heavy, third-row transition metal in group 7 of the periodic table. With an estimated average concentration of 1 part per billion (ppb), rhenium is one of the rarest elements in the Earth's crust.",
    electron_configuration: "[Xe] 4f14 5d5 6s2",
    cpk_hex: "2185ad"
  },
  {
    number: 76,
    symbol: "Os",
    name: "Osmium",
    atomic_mass: 190.23,
    category: "transition metal",
    group: 8,
    period: 6,
    phase: "Solid",
    appearance: "silvery blue cast",
    boiling_point: 5285,
    melting_point: 3306,
    density: 22.59,
    summary: "Osmium is a chemical element with symbol Os and atomic number 76. It is a hard, brittle, bluish-white transition metal in the platinum group that is found as a trace element in alloys, mostly in platinum ores. Osmium is the densest naturally occurring element.",
    electron_configuration: "[Xe] 4f14 5d6 6s2",
    cpk_hex: "267db0"
  },
  {
    number: 77,
    symbol: "Ir",
    name: "Iridium",
    atomic_mass: 192.22,
    category: "transition metal",
    group: 9,
    period: 6,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 4403,
    melting_point: 2719,
    density: 22.56,
    summary: "Iridium is a chemical element with symbol Ir and atomic number 77. A very hard, brittle, silvery-white transition metal of the platinum group, iridium is generally credited with being the second densest element (after osmium) based on measured density, although calculations involving the space lattices of the elements show that iridium is denser.",
    electron_configuration: "[Xe] 4f14 5d7 6s2",
    cpk_hex: "175487"
  },
  {
    number: 81,
    symbol: "Tl",
    name: "Thallium",
    atomic_mass: 204.38,
    category: "post-transition metal",
    group: 13,
    period: 6,
    phase: "Solid",
    appearance: "silvery white, tarnishes to gray",
    boiling_point: 1746,
    melting_point: 577,
    density: 11.85,
    summary: "Thallium is a chemical element with symbol Tl and atomic number 81. This soft gray post-transition metal is not found free in nature. When isolated, thallium resembles tin, but discolors when exposed to air.",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p1",
    cpk_hex: "a6544d"
  },
  {
    number: 83,
    symbol: "Bi",
    name: "Bismuth",
    atomic_mass: 208.98,
    category: "post-transition metal",
    group: 15,
    period: 6,
    phase: "Solid",
    appearance: "lustrous silver with a pinkish tinge",
    boiling_point: 1837,
    melting_point: 544.7,
    density: 9.78,
    summary: "Bismuth is a chemical element with symbol Bi and atomic number 83. Bismuth, a pentavalent post-transition metal, chemically resembles arsenic and antimony. Elemental bismuth may occur naturally, although its sulfide and oxide form important commercial ores.",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p3",
    cpk_hex: "9e4fb5"
  },
  {
    number: 84,
    symbol: "Po",
    name: "Polonium",
    atomic_mass: 209,
    category: "post-transition metal",
    group: 16,
    period: 6,
    phase: "Solid",
    appearance: "silvery",
    boiling_point: 1235,
    melting_point: 527,
    density: 9.196,
    summary: "Polonium is a chemical element with symbol Po and atomic number 84, discovered in 1898 by Marie Curie and Pierre Curie. A rare and highly radioactive element with no stable isotopes, polonium is chemically similar to bismuth and tellurium, and it occurs in uranium ores.",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p4",
    cpk_hex: "ab5c00"
  },
  {
    number: 85,
    symbol: "At",
    name: "Astatine",
    atomic_mass: 210,
    category: "metalloid",
    group: 17,
    period: 6,
    phase: "Solid",
    appearance: "unknown, probably metallic",
    boiling_point: 610,
    melting_point: 575,
    density: 7,
    summary: "Astatine is a very rare radioactive chemical element with the chemical symbol At and atomic number 85. It occurs on Earth as the decay product of various heavier elements. All its isotopes are short-lived; the most stable is astatine-210, with a half-life of 8.1 hours.",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p5",
    cpk_hex: "752e00"
  },
  {
    number: 86,
    symbol: "Rn",
    name: "Radon",
    atomic_mass: 222,
    category: "noble gas",
    group: 18,
    period: 6,
    phase: "Gas",
    appearance: "colorless gas, occasionally glows yellow when cooled below its freezing point",
    boiling_point: 211.5,
    melting_point: 202,
    density: 9.73,
    summary: "Radon is a chemical element with symbol Rn and atomic number 86. It is a radioactive, colorless, odorless, tasteless noble gas, occurring naturally as a decay product of radium. Its most stable isotope, 222Rn, has a half-life of 3.8 days.",
    electron_configuration: "[Xe] 4f14 5d10 6s2 6p6",
    cpk_hex: "428296"
  },
  {
    number: 87,
    symbol: "Fr",
    name: "Francium",
    atomic_mass: 223,
    category: "alkali metal",
    group: 1,
    period: 7,
    phase: "Solid",
    appearance: null,
    boiling_point: 950,
    melting_point: 300,
    density: 1.87,
    summary: "Francium is a chemical element with symbol Fr and atomic number 87. It was formerly known as eka-caesium and actinium K. It is the second least electronegative element, behind only caesium, and is the second rarest naturally occurring element (after astatine).",
    electron_configuration: "[Rn] 7s1",
    cpk_hex: "420066"
  },
  {
    number: 88,
    symbol: "Ra",
    name: "Radium",
    atomic_mass: 226,
    category: "alkaline earth metal",
    group: 2,
    period: 7,
    phase: "Solid",
    appearance: "silvery white metallic",
    boiling_point: 2013,
    melting_point: 973,
    density: 5.5,
    summary: "Radium is a chemical element with symbol Ra and atomic number 88. It is the sixth element in group 2 of the periodic table, also known as the alkaline earth metals. Pure radium is silvery-white, but it readily combines with nitrogen (rather than oxygen) on exposure to air, forming a black surface layer of radium nitride (Ra3N2).",
    electron_configuration: "[Rn] 7s2",
    cpk_hex: "006600"
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Actinium",
    atomic_mass: 227,
    category: "actinide",
    group: 3,
    period: 7,
    phase: "Solid",
    appearance: null,
    boiling_point: 3471,
    melting_point: 1323,
    density: 10,
    summary: "Actinium is a radioactive chemical element with symbol Ac and atomic number 89, which was discovered in 1899. It was the first non-primordial radioactive element to be isolated. Polonium, radium and radon were observed before actinium, but they were not isolated until 1902.",
    electron_configuration: "[Rn] 6d1 7s2",
    cpk_hex: "70abfa"
  },
  {
    number: 91,
    symbol: "Pa",
    name: "Protactinium",
    atomic_mass: 231.04,
    category: "actinide",
    group: 3,
    period: 9,
    phase: "Solid",
    appearance: "bright, silvery metallic luster",
    boiling_point: 4300,
    melting_point: 1841,
    density: 15.37,
    summary: "Protactinium is a chemical element with symbol Pa and atomic number 91. It is a dense, silvery-gray metal which readily reacts with oxygen, water vapor and inorganic acids. It forms several chemical compounds in which protactinium is usually present in the oxidation state +5, but it can also assume +4 and even +2 or +3 states.",
    electron_configuration: "[Rn] 5f2 6d1 7s2",
    cpk_hex: "00a1ff"
  },
  {
    number: 93,
    symbol: "Np",
    name: "Neptunium",
    atomic_mass: 237,
    category: "actinide",
    group: 3,
    period: 9,
    phase: "Solid",
    appearance: "silvery metallic",
    boiling_point: 4174,
    melting_point: 912,
    density: 20.45,
    summary: "Neptunium is a chemical element with symbol Np and atomic number 93. A radioactive actinide metal, neptunium is the first transuranic element. Its position in the periodic table just after uranium, named after the planet Uranus, led to it being named after Neptune, the next planet beyond Uranus.",
    electron_configuration: "[Rn] 5f4 6d1 7s2",
    cpk_hex: "008fff"
  },
  {
    number: 94,
    symbol: "Pu",
    name: "Plutonium",
    atomic_mass: 244,
    category: "actinide",
    group: 3,
    period: 9,
    phase: "Solid",
    appearance: "silvery white, tarnishing to dark gray in air",
    boiling_point: 3505,
    melting_point: 912.5,
    density: 19.816,
    summary: "Plutonium is a transuranic radioactive chemical element with symbol Pu and atomic number 94. It is an actinide metal of silvery-gray appearance that tarnishes when exposed to air, and forms a dull coating when oxidized.",
    electron_configuration: "[Rn] 5f6 7s2",
    cpk_hex: "007bff"
  },
  {
    number: 95,
    symbol: "Am",
    name: "Americium",
    atomic_mass: 243,
    category: "actinide",
    group: 3,
    period: 9,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 2880,
    melting_point: 1449,
    density: 12,
    summary: "Americium is a radioactive transuranic chemical element with symbol Am and atomic number 95. This member of the actinide series is located in the periodic table under the lanthanide element europium, and thus by analogy was named after the Americas.",
    electron_configuration: "[Rn] 5f7 7s2",
    cpk_hex: "545cf2"
  },
  {
    number: 96,
    symbol: "Cm",
    name: "Curium",
    atomic_mass: 247,
    category: "actinide",
    group: 3,
    period: 9,
    phase: "Solid",
    appearance: "silvery metallic, glows purple in the dark",
    boiling_point: 3383,
    melting_point: 1613,
    density: 13.51,
    summary: "Curium is a transuranic radioactive chemical element with symbol Cm and atomic number 96. This element of the actinide series was named after Marie and Pierre Curie – both were known for their research on radioactivity.",
    electron_configuration: "[Rn] 5f7 6d1 7s2",
    cpk_hex: "785ce3"
  },
  {
    number: 97,
    symbol: "Bk",
    name: "Berkelium",
    atomic_mass: 247,
    category: "actinide",
    group: 3,
    period: 9,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 2900,
    melting_point: 1259,
    density: 14.78,
    summary: "Berkelium is a transuranic radioactive chemical element with symbol Bk and atomic number 97. It is a member of the actinide and transuranium element series. It is named after the city of Berkeley, California, the location of the University of California Radiation Laboratory where it was discovered in December 1949.",
    electron_configuration: "[Rn] 5f9 7s2",
    cpk_hex: "8a4fe3"
  },
  {
    number: 98,
    symbol: "Cf",
    name: "Californium",
    atomic_mass: 251,
    category: "actinide",
    group: 3,
    period: 9,
    phase: "Solid",
    appearance: "silvery",
    boiling_point: 1743,
    melting_point: 1173,
    density: 15.1,
    summary: "Californium is a transuranic radioactive chemical element with symbol Cf and atomic number 98. The element was first synthesized in 1950 at the University of California Radiation Laboratory in Berkeley, by bombarding curium with alpha particles.",
    electron_configuration: "[Rn] 5f10 7s2",
    cpk_hex: "a136d4"
  },
  {
    number: 99,
    symbol: "Es",
    name: "Einsteinium",
    atomic_mass: 252,
    category: "actinide",
    group: 3,
    period: 9,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 1269,
    melting_point: 1133,
    density: 8.84,
    summary: "Einsteinium is a transuranic radioactive chemical element with symbol Es and atomic number 99. Einsteinium was discovered as a component of the debris of the first hydrogen bomb explosion in 1952, and named after Albert Einstein.",
    electron_configuration: "[Rn] 5f11 7s2",
    cpk_hex: "b31fd4"
  },
  {
    number: 100,
    symbol: "Fm",
    name: "Fermium",
    atomic_mass: 257,
    category: "actinide",
    group: 3,
    period: 9,
    phase: "Solid",
    appearance: null,
    boiling_point: null,
    melting_point: 1800,
    density: null,
    summary: "Fermium is a transuranic radioactive chemical element with symbol Fm and atomic number 100. It is an actinide and the heaviest element that can be formed by neutron bombardment of lighter elements, and hence the last element that can be prepared in macroscopic quantities, although pure fermium metal has not yet been prepared.",
    electron_configuration: "[Rn] 5f12 7s2",
    cpk_hex: "b31fba"
  },
  {
    number: 101,
    symbol: "Md",
    name: "Mendelevium",
    atomic_mass: 258,
    category: "actinide",
    group: 3,
    period: 9,
    phase: "Solid",
    appearance: null,
    boiling_point: null,
    melting_point: 1100,
    density: null,
    summary: "Mendelevium is a synthetic element with symbol Md and atomic number 101. A transuranic radioactive element in the actinide series, it is the first element that currently cannot be produced in macroscopic quantities through neutron bombardment of lighter elements. It is the third-to-last actinide and the ninth transuranic element.",
    electron_configuration: "[Rn] 5f13 7s2",
    cpk_hex: "b30da6"
  },
  {
    number: 102,
    symbol: "No",
    name: "Nobelium",
    atomic_mass: 259,
    category: "actinide",
    group: 3,
    period: 9,
    phase: "Solid",
    appearance: null,
    boiling_point: null,
    melting_point: 1100,
    density: null,
    summary: "Nobelium is a synthetic chemical element with symbol No and atomic number 102. It is named in honor of Alfred Nobel, the inventor of dynamite and benefactor of science. A radioactive metal, it is the tenth transuranic element and is the penultimate member of the actinide series.",
    electron_configuration: "[Rn] 5f14 7s2",
    cpk_hex: "bd0d87"
  },
  {
    number: 103,
    symbol: "Lr",
    name: "Lawrencium",
    atomic_mass: 266,
    category: "actinide",
    group: 3,
    period: 9,
    phase: "Solid",
    appearance: null,
    boiling_point: null,
    melting_point: 1900,
    density: null,
    summary: "Lawrencium is a synthetic chemical element with symbol Lr and atomic number 103. It is named in honor of Ernest Lawrence, inventor of the cyclotron, a device that was used to discover many artificial radioactive elements. A radioactive metal, lawrencium is the eleventh transuranic element and is also the final member of the actinide series.",
    electron_configuration: "[Rn] 5f14 7s2 7p1",
    cpk_hex: "c70066"
  },
  {
    number: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    atomic_mass: 267,
    category: "transition metal",
    group: 4,
    period: 7,
    phase: "Solid",
    appearance: null,
    boiling_point: 5800,
    melting_point: 2400,
    density: 23.2,
    summary: "Rutherfordium is a synthetic chemical element with symbol Rf and atomic number 104, named after physicist Ernest Rutherford. It is a synthetic element and radioactive; the most stable known isotope is 267Rf, which has a half-life of approximately 1.3 hours.",
    electron_configuration: "[Rn] 5f14 6d2 7s2",
    cpk_hex: "cc0059"
  },
  {
    number: 105,
    symbol: "Db",
    name: "Dubnium",
    atomic_mass: 268,
    category: "transition metal",
    group: 5,
    period: 7,
    phase: "Solid",
    appearance: null,
    boiling_point: null,
    melting_point: null,
    density: 29.3,
    summary: "Dubnium is a chemical element with symbol Db and atomic number 105, named after the town of Dubna in Russia, where it was first produced. It is a synthetic element and radioactive; the most stable known isotope, dubnium-268, has a half-life of approximately 28 hours.",
    electron_configuration: "[Rn] 5f14 6d3 7s2",
    cpk_hex: "d1004f"
  },
  {
    number: 106,
    symbol: "Sg",
    name: "Seaborgium",
    atomic_mass: 269,
    category: "transition metal",
    group: 6,
    period: 7,
    phase: "Solid",
    appearance: null,
    boiling_point: null,
    melting_point: null,
    density: 35,
    summary: "Seaborgium is a synthetic chemical element with symbol Sg and atomic number 106. It is named after the American nuclear chemist Glenn T. Seaborg. As a synthetic element, it can be created in a laboratory but is not found in nature. It is also radioactive; the most stable known isotope, 269Sg, has a half-life of approximately 3.1 minutes.",
    electron_configuration: "[Rn] 5f14 6d4 7s2",
    cpk_hex: "d90045"
  },
  {
    number: 107,
    symbol: "Bh",
    name: "Bohrium",
    atomic_mass: 270,
    category: "transition metal",
    group: 7,
    period: 7,
    phase: "Solid",
    appearance: null,
    boiling_point: null,
    melting_point: null,
    density: 37,
    summary: "Bohrium is a synthetic chemical element with symbol Bh and atomic number 107. It is named after Danish physicist Niels Bohr. As a synthetic element, it can be created in a laboratory but is not found in nature. All known isotopes of bohrium are extremely radioactive; the most stable known isotope is 270Bh with a half-life of approximately 61 seconds.",
    electron_configuration: "[Rn] 5f14 6d5 7s2",
    cpk_hex: "e00038"
  },
  {
    number: 108,
    symbol: "Hs",
    name: "Hassium",
    atomic_mass: 269,
    category: "transition metal",
    group: 8,
    period: 7,
    phase: "Solid",
    appearance: null,
    boiling_point: null,
    melting_point: null,
    density: 41,
    summary: "Hassium is a synthetic chemical element with symbol Hs and atomic number 108, named after the German state of Hesse. It is a synthetic element and radioactive; the most stable known isotope, 270Hs, has a half-life of approximately 10 seconds.",
    electron_configuration: "[Rn] 5f14 6d6 7s2",
    cpk_hex: "e6002e"
  },
  {
    number: 109,
    symbol: "Mt",
    name: "Meitnerium",
    atomic_mass: 278,
    category: "transition metal",
    group: 9,
    period: 7,
    phase: "Solid",
    appearance: null,
    boiling_point: null,
    melting_point: null,
    density: 37.4,
    summary: "Meitnerium is a synthetic chemical element with symbol Mt and atomic number 109. It is an extremely radioactive synthetic element (an element that can be created in a laboratory but is not found in nature); the most stable known isotope, meitnerium-278, has a half-life of 7.6 seconds.",
    electron_configuration: "[Rn] 5f14 6d7 7s2",
    cpk_hex: "eb0024"
  },
  {
    number: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    atomic_mass: 281,
    category: "transition metal",
    group: 10,
    period: 7,
    phase: "Solid",
    appearance: null,
    boiling_point: null,
    melting_point: null,
    density: 34.8,
    summary: "Darmstadtium is a chemical element with symbol Ds and atomic number 110. It is an extremely radioactive synthetic element. The most stable known isotope, darmstadtium-281, has an estimated half-life of around 12.7 seconds.",
    electron_configuration: "[Rn] 5f14 6d9 7s1",
    cpk_hex: "f00017"
  },
  {
    number: 111,
    symbol: "Rg",
    name: "Roentgenium",
    atomic_mass: 282,
    category: "transition metal",
    group: 11,
    period: 7,
    phase: "Solid",
    appearance: null,
    boiling_point: null,
    melting_point: null,
    density: 28.7,
    summary: "Roentgenium is a chemical element with symbol Rg and atomic number 111. It is an extremely radioactive synthetic element (an element that can be created in a laboratory but is not found in nature); the most stable known isotope, roentgenium-282, has a half-life of 2.1 minutes.",
    electron_configuration: "[Rn] 5f14 6d10 7s1",
    cpk_hex: "f5000a"
  },
  {
    number: 112,
    symbol: "Cn",
    name: "Copernicium",
    atomic_mass: 285,
    category: "transition metal",
    group: 12,
    period: 7,
    phase: "Gas",
    appearance: null,
    boiling_point: 357,
    melting_point: null,
    density: 23.7,
    summary: "Copernicium is a chemical element with symbol Cn and atomic number 112. It is an extremely radioactive synthetic element that can only be created in a laboratory. The most stable known isotope, copernicium-285, has a half-life of approximately 29 seconds.",
    electron_configuration: "[Rn] 5f14 6d10 7s2",
    cpk_hex: "ff005c"
  },
  {
    number: 113,
    symbol: "Nh",
    name: "Nihonium",
    atomic_mass: 286,
    category: "post-transition metal",
    group: 13,
    period: 7,
    phase: "Solid",
    appearance: null,
    boiling_point: 1400,
    melting_point: 700,
    density: 16,
    summary: "Nihonium is a synthetic chemical element with symbol Nh and atomic number 113. It is extremely radioactive; its most stable known isotope, nihonium-286, has a half-life of 20 seconds. In the periodic table, nihonium is a transactinide element in the p-block. It is a member of period 7 and group 13.",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p1",
    cpk_hex: "ff0070"
  },
  {
    number: 114,
    symbol: "Fl",
    name: "Flerovium",
    atomic_mass: 289,
    category: "post-transition metal",
    group: 14,
    period: 7,
    phase: "Solid",
    appearance: null,
    boiling_point: 420,
    melting_point: 340,
    density: 14,
    summary: "Flerovium is a superheavy synthetic chemical element with symbol Fl and atomic number 114. It is an extremely radioactive transactinide element. The element is named after the Flerov Laboratory of Nuclear Reactions of the Joint Institute for Nuclear Research in Dubna, Russia, where the element was discovered in 1998.",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p2",
    cpk_hex: "ff0085"
  },
  {
    number: 115,
    symbol: "Mc",
    name: "Moscovium",
    atomic_mass: 290,
    category: "post-transition metal",
    group: 15,
    period: 7,
    phase: "Solid",
    appearance: null,
    boiling_point: 1400,
    melting_point: 670,
    density: 13.5,
    summary: "Moscovium is a synthetic chemical element with symbol Mc and atomic number 115. It was first synthesized in 2003 by a joint team of Russian and American scientists at the Joint Institute for Nuclear Research (JINR) in Dubna, Russia.",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p3",
    cpk_hex: "ff009c"
  },
  {
    number: 116,
    symbol: "Lv",
    name: "Livermorium",
    atomic_mass: 293,
    category: "post-transition metal",
    group: 16,
    period: 7,
    phase: "Solid",
    appearance: null,
    boiling_point: 1085,
    melting_point: 709,
    density: 12.9,
    summary: "Livermorium is a synthetic chemical element with symbol Lv and atomic number 116. It is an extremely radioactive element that can only be created in a laboratory and has not been observed in nature. The element is named after the Lawrence Livermore National Laboratory in the United States, which collaborated with the Joint Institute for Nuclear Research in Dubna, Russia to discover livermorium in 2000.",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p4",
    cpk_hex: "ff00b3"
  },
  {
    number: 117,
    symbol: "Ts",
    name: "Tennessine",
    atomic_mass: 294,
    category: "metalloid",
    group: 17,
    period: 7,
    phase: "Solid",
    appearance: null,
    boiling_point: 883,
    melting_point: 723,
    density: 7.2,
    summary: "Tennessine is a synthetic chemical element with symbol Ts and atomic number 117. It is the second-heaviest known element and the penultimate element of the 7th period of the periodic table.",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p5",
    cpk_hex: "ff00d4"
  },
  {
    number: 54,
    symbol: "Xe",
    name: "Xenon",
    atomic_mass: 131.29,
    category: "noble gas",
    group: 18,
    period: 5,
    phase: "Gas",
    appearance: "colorless gas, exhibiting a blue glow in a high voltage electric field",
    boiling_point: 165.03,
    melting_point: 161.4,
    density: 5.894,
    summary: "Xenon is a chemical element with symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas found in Earth's atmosphere in trace amounts.",
    electron_configuration: "[Kr] 4d10 5s2 5p6",
    cpk_hex: "429eb0"
  },
  {
    number: 55,
    symbol: "Cs",
    name: "Caesium",
    atomic_mass: 132.91,
    category: "alkali metal",
    group: 1,
    period: 6,
    phase: "Solid",
    appearance: "silvery gold",
    boiling_point: 944,
    melting_point: 301.59,
    density: 1.93,
    summary: "Caesium is a chemical element with symbol Cs and atomic number 55. It is a soft, silvery-gold alkali metal with a melting point of 28.5 °C (83.3 °F), which makes it one of only five elemental metals that are liquid at or near room temperature.",
    electron_configuration: "[Xe] 6s1",
    cpk_hex: "57178f"
  },
  {
    number: 56,
    symbol: "Ba",
    name: "Barium",
    atomic_mass: 137.33,
    category: "alkaline earth metal",
    group: 2,
    period: 6,
    phase: "Solid",
    appearance: null,
    boiling_point: 2118,
    melting_point: 1000,
    density: 3.51,
    summary: "Barium is a chemical element with symbol Ba and atomic number 56. It is the fifth element in group 2 and is a soft, silvery alkaline earth metal. Because of its high chemical reactivity, barium is never found in nature as a free element.",
    electron_configuration: "[Xe] 6s2",
    cpk_hex: "00c900"
  },
  {
    number: 74,
    symbol: "W",
    name: "Tungsten",
    atomic_mass: 183.84,
    category: "transition metal",
    group: 6,
    period: 6,
    phase: "Solid",
    appearance: "grayish white, lustrous",
    boiling_point: 6203,
    melting_point: 3695,
    density: 19.3,
    summary: "Tungsten, also known as wolfram, is a chemical element with symbol W and atomic number 74. Tungsten is a rare metal found naturally on Earth almost exclusively as compounds with other elements. It was identified as a new element in 1781 and first isolated as a metal in 1783.",
    electron_configuration: "[Xe] 4f14 5d4 6s2",
    cpk_hex: "2194d6"
  },
  {
    number: 78,
    symbol: "Pt",
    name: "Platinum",
    atomic_mass: 195.08,
    category: "transition metal",
    group: 10,
    period: 6,
    phase: "Solid",
    appearance: "silvery white",
    boiling_point: 4098,
    melting_point: 2041.4,
    density: 21.45,
    summary: "Platinum is a chemical element with symbol Pt and atomic number 78. It is a dense, malleable, ductile, highly unreactive, precious, silver-white transition metal. Its name is derived from the Spanish term platina, which is literally translated into 'little silver'.",
    electron_configuration: "[Xe] 4f14 5d9 6s1",
    cpk_hex: "d0d0e0"
  },
  {
    number: 118,
    symbol: "Og",
    name: "Oganesson",
    atomic_mass: 294,
    category: "noble gas",
    group: 18,
    period: 7,
    phase: "Gas",
    appearance: null,
    boiling_point: 350,
    melting_point: null,
    density: null,
    summary: "Oganesson is a synthetic chemical element with symbol Og and atomic number 118. It was first synthesized in 2002 at the Joint Institute for Nuclear Research in Dubna, Russia.",
    electron_configuration: "[Rn] 5f14 6d10 7s2 7p6",
    cpk_hex: "ff00eb"
  },
];
